# For preview deployment only… maybe?
routes:
  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    data: page.blog
  /:
    permalink: /{slug}/
    template: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
