# For preview deployment only… maybe?
routes:
  /:
    data: page.home
    template: home
  /get-involved/:
    data: page.get-involved
    template: page-get-involved

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    data: page.blog
    filter: tag:-[newsletter, newslettertest]
  /newsletters/:
    permalink: /newsletters/{slug}/
    filter: tag:newsletter
    data: page.newsletters
  /:
    permalink: /{slug}/
    template: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
