name: Deploy theme to sandbox
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo ::set-env name=PR_BRANCH_NAME::${BRANCH_NAME}
      - run: npm run action-version
      - uses: TryGhost/action-deploy-theme@v1.3.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: wpch-${{ env.PR_BRANCH_NAME }}
