name: Destroy preview
on:
  pull_request:
    types: [closed]
jobs:
  destroy:
    runs-on: ubuntu-18.04
    steps:
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo ::set-env name=PR_BRANCH_NAME::${BRANCH_NAME}
      - name: destroy application
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku apps:destroy ghostprev-${PR_BRANCH_NAME} -c=ghostprev-${PR_BRANCH_NAME}
