name: Destroy preview
on:
  pull_request:
    types: [closed]
jobs:
  destroy:
    runs-on: ubuntu-18.04
    steps:
      - uses: igordcsouza/github-action-get-branch-name@ecf5862
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set branch name as PR_BRANCH_NAME
        run: echo "PR_BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: Store Heroku app name
        run: echo "APP_NAME=`echo ghostprev-${PR_BRANCH_NAME} | cut -c 1-30 | tr _ - | tr '[:upper:]' '[:lower:]' | sed -e 's/-$//' | sed -e 's/[^a-z0-9\-]//g'`" >> $GITHUB_ENV
      - name: destroy application
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku apps:destroy $APP_NAME -c=$APP_NAME
